[package]
name = "day11"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
common = { version = "0.1.0", path = "../common" }
pathfinding.workspace = true
petgraph.workspace = true
