[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
common = { version = "0.1.0", path = "../common" }
nom.workspace = true
pathfinding.workspace = true
rayon.workspace = true
